About me/this is me #3
front-end-by-rimantas/20-grupe-portfolio-personal pull request #35
Opened 2020-12-31 13:35 UTC by Justas383

-this is me
-about me
-responsive
-font weight 200

2020-12-31 15:25 UTC, vikontrimaite requested changes
Kai screen size būna 320px, tada lieka per daug tuščios erdvės (margin) iš šonų. Pridedu paveiksliuką  https://ibb.co/d7TckfS . Man padėjo šito default'ino nustatymo ištrynimas, bet pas tave nesuveikia https://ibb.co/qyVS8wP :smiley: Ties 
@media (max-width: 768px)
.this-is-me-left {
    /* margin-left: 10%; */
    /* margin-right: 10%; */
}

nuėmus margin'us ir

@media (max-width: 576px)
.this-is-me-left {
    width: 100%;
}

uždėjus 100% situacija kiek geresnė :smile: O šiaip sakė, kad naudosim min-width, o ne max-width, tai gal ir čia problema :smile: 

Ant 576px screen ta pati situacija :smile: Gal reiktų heading, p ir button uždėti flexbox'ą, o paveiksliukui ne? Nes paveiksliuko platumas kitoks :) 

+
'this is me' atrodo per plonai parašyta, o Filipo vardas kiek per didelis.

Ties 756px dar labiau matosi, kad pas tave ir tekstas ir img lygiuojasi, nors orginale nesilygiuoja :) Su antru paveiksliuku viskas atrodo gerai.  

Nuo 992px jau puikiai kaip ir priklauso nebesilygiuoja img ir tekstai! Taip pat ties šituo atsiranda balta linija iš šono, tai gal reikėtų čia išimti margin'ą https://ibb.co/C91rSn8 . Ir pirmas Filipo img turėtų nesilieti su background'o apačią, dar lieka tarp :)

Pažiūrėjus į patį kodą: about.css font-family atskirai nereikia nurodyti, nes jau reset.css yra nurodytas. Ir šiaip blogai parašyta, reikėtų rašyti 'Poppins' iš didžiosios ir tarp kabučių :D 

.about-me-left{} tieisog tuščią palikai, tai jei nereikia, trink lauk :wink: 

Ir pačiam html'e: šiandien išsiaiškinau, kad nebūtina visų taip surašyti 'col-xs-12 col-sm-12 col-md-6 col-lg-6'. Užtenka rašyti tik tą, kuris mažesnis, ir didesnis jį perims, o tada rašyti tik tą, ant kurio vėl keičiasi. Taigi tau gautųsi 'col-xs-12 col-md-6'. 
Arba 'col-xs-12 col-sm-12 col-md-12 col-lg-12' --> 'col-12'

Dar button'ui trūksta hover'inimo dalies. Toks kaip ir šešėlis turi būti į apačią, pažiūrėk orginale, pabandyk kažką turbūt su box-shadow ant btn:hover button.css 

Tai va tiek :sweat_smile: Šiaip bendras vaizdas visai gerai atrodo, ypatingai p dydis, paveiksliukai ir button išvis superinis :+1:

2021-01-01 22:31 UTC, arturas-vei submitted a review, later dismissed

2021-01-02 16:35 UTC, vikontrimaite reviewed
Viskas daug geriau atrodo, button'o hoverinimas puikus!!
Kaip ir tarėmės, siūlau dar kiek paddingo iš kairės uždėti ir paveiksliuko dydį sumažinti :smile: Ir teksto po Philip'o vardo kiek mažesnis width į šonus turėtų būti :thinking:

2021-01-02 17:20 UTC, VytautasKaz commented on css/components/button.css
> +    box-shadow: 0px 0px  0px var(--main-color);
Nežinau, ar labai svarbu, bet du tarpai padėti po antro '0px'.

2021-01-02 17:26 UTC, VytautasKaz commented on css/components/button.css
> +.btn-hero {
Mygtuke esančio šrifto font-weight galėtų būt didesnis, pabandžiau 550, nebuvo identiškai su OG dizainu, bet atrodė galbūt kiek geriau.

2021-01-02 17:42 UTC, VytautasKaz requested changes
Pora labai lengvai pakeičiamų dalykėlių. Galbūt kabinėjuos, bet dar nežinau, kaip griežtai vertint reikia. Bendrai - puikiai padirbėta.

2021-01-03 12:03 UTC, VytautasKaz approved these changes

2021-01-03 12:22 UTC, vikontrimaite approved these changes
Looks really good now! Good job! :smiley:

2021-01-03 12:30 UTC, justasga approved these changes

2021-01-03 12:31 UTC, merged