Create services section #4
front-end-by-rimantas/20-grupe-portfolio-personal pull request #36
Opened 2020-12-31 14:46 UTC by vikontrimaite

-when you hover on single service item, only icon and heading change the color (but not p)!
-positioning service items 

-gali reikėti dar kažkiek redaguoti išsidėstymą, kai aplink matysis kitos sekcijos :)

2020-12-31 15:07 UTC, belauzas requested changes

2020-12-31 15:07 UTC, belauzas commented on css/components/services.css
> +.service-item:hover > h1:not(:hover){
Pirma - parašyti `h1:not(:hover)` yra tas pats kas parašyti `h1`, tad ištriname nereikalingą dalį.
Antra - `h1` tag'as puslapyje gali būti tik vienas - reiškia, reikia jį pakeisti į kiek mažiau reikšmingą, pvz `h3`.

2020-12-31 15:07 UTC, belauzas commented on css/components/services.css
> +.service-item:hover > i:not(:hover){
Parašyti `i:not(:hover)` yra tas pats kas parašyti `i`, tad ištriname nereikalingą dalį.

2020-12-31 15:07 UTC, belauzas commented on css/components/services.css
> +  -webkit-background-clip: text;
Jei parašome tikslinančius prefiksus, tai prieš tai reikia parašyti ir standartinę savybę, šiuo atveju `background-clip`.

2020-12-31 15:07 UTC, belauzas commented on css/components/services.css
> +  -webkit-background-clip: text;
Jei parašome tikslinančius prefiksus, tai prieš tai reikia parašyti ir standartinę savybę, šiuo atveju `background-clip`.

2020-12-31 15:07 UTC, belauzas commented on css/components/services.css
> +  -webkit-background-clip: text;
Jei parašome tikslinančius prefiksus, tai prieš tai reikia parašyti ir standartinę savybę, šiuo atveju `background-clip`.

2020-12-31 15:07 UTC, belauzas commented on css/components/services.css
> +    /* margin: 0 .2rem; */
Pašalinti komentarus, kai kodas keliauja į `develop` ar `master` branch'us.

2020-12-31 15:34 UTC, vikontrimaite commented on css/components/services.css
> +.service-item:hover > h1:not(:hover){
Aš kiek supratau, jog parašydama čia '>' nurodau, kad turiu omenyje būtent tą h1, kurio tėvas yra .service-item? Nes pahover'inus ant mano section'o esančio pagrindinio h1 jis nesikeičia.

2020-12-31 15:39 UTC, vikontrimaite commented on css/components/services.css
> +  -webkit-background-clip: text;
Nelabai supratau, ką konkrečiai siūlote pakeisti. Ar pridėti eilutę `-webkit-background-clip: background-clip;`? 
Čia tiesiog rėmiausi pavyzdžiu, kurį radau paguglinus, svarbiausia, kad veikia :smile:

2020-12-31 15:40 UTC, belauzas commented on css/components/services.css
> +  -webkit-background-clip: text;
```
background-clip: text;
-webkit-background-clip: text;
```

2020-12-31 15:43 UTC, belauzas commented on css/components/services.css
> +.service-item:hover > h1:not(:hover){
Esmė, jog parašius `element:not(:hover)` yra pasakoma, jog kai kursorius nėra ant pasirinkto elemento... o tai reiškia, jog norima matyti standartinį elemento stilių, lyg būtų parašyta `element`, t.y. abu selectoriai daro tą patį.

2021-01-01 22:31 UTC, arturas-vei approved these changes

2021-01-02 17:12 UTC, belauzas approved these changes

2021-01-02 18:10 UTC, VytautasKaz approved these changes
Looks great!

2021-01-02 18:10 UTC, merged