Footer
front-end-by-rimantas/20-grupe-portfolio-personal pull request #47
Opened 2021-01-03 20:34 UTC by justasga

Arrow icon is missing inside button
Margins may need to be fixed

2021-01-04 07:28 UTC, vikontrimaite requested changes
Gerai padirbėjai! Parašiau keletą komentarų, ką dar gali patobulinti :smiley: Sėkmės!

2021-01-04 07:28 UTC, vikontrimaite commented on index.html
> +                </button>
čia yra arrows'ai, tai gali reikiamos rodyklės kodą įdėti ir bus rodyklė https://www.w3schools.com/charsets/ref_utf_arrows.asp :smile:

2021-01-04 07:28 UTC, vikontrimaite commented on css/components/footer.css
> +footer {
duok jam dar `padding-top` ir `padding-bottom` (kaip kad orginale, ten daugokai vietos duoda :smiley: )

2021-01-04 07:28 UTC, vikontrimaite commented on css/components/footer.css
> +footer {
ok, nežinau, kurioje vietoje pridėti komenatarą, bet va: ant 576px screen width turėtų būti kiek kitoks footer'io išsidėstymas: pas tave eina viskas iš eilės, o orginale kiek kitaip išsidėsto https://ibb.co/6v4TkDY

2021-01-04 07:28 UTC, vikontrimaite commented on css/components/footer.css
> +footer {
tas pats ir ant 768px :) gal čia grid'o reikia su grid-template-areas? :thinking:

2021-01-04 07:28 UTC, vikontrimaite commented on css/components/footer.css
> +footer a {
ant 992px screen width pas tave viena ikona nušoka į apačią ir netelpa prie kitų.. :smile:

2021-01-04 07:33 UTC, vikontrimaite commented on index.html
> +                <p>Copyright &copy; 2020 All rights reserved | This template is made with &hearts; by <span>Colorlib &amp; BIT students </span></p>
Colorlib &amp; BIT students - čia nuoroda `a` dar turi būti :)

2021-01-04 07:56 UTC, Justas383 requested changes
Reikėtu nuimti borderį nuo mygtuko ir idėti rodyklę, nes dabar atrodo jog nesilygiuoja. taip pat ta pati problema ,apie ką kalbejo Vilija. dėl lygiavimo ties 76x px. turėtų kitaip susilygiuoti, negu kad eiti viskas is eilės. Kai susilygiuoja viskas į vieną stulpelį, lieka perdaug tuščios erdvės apačioje.  O visa kitą atrodo neblogai, gerai padirbėta :) 💯

2021-01-05 09:52 UTC, vikontrimaite approved these changes
Super, viskas yra taip, kaip ir reikia! :smiley:

2021-01-05 15:23 UTC, arturas-vei approved these changes

2021-01-05 20:51 UTC, Justas383 approved these changes
all good. bet enter email laukelis, atrodo jog butu su labai smulkiu borderiu.

2021-01-05 20:52 UTC, merged