Featured projects
front-end-by-rimantas/20-grupe-portfolio-personal pull request #49
Opened 2021-01-04 09:09 UTC by juliusvara

2021-01-04 09:18 UTC, vikontrimaite requested changes
196 eilutėje prasideda BLOG section, o ne PROJECTS, perkelk kur reikia HTML'ą (PROJECTS prasideda 165 eilutėje) :smile:

2021-01-04 09:18 UTC, vikontrimaite commented on index.html
> -                    Blog CONTENT
196 eilutėje prasideda BLOG section, o ne PROJECTS, perkelk kur reikia HTML'ą (PROJECTS prasideda 165 eilutėje) :smile:

2021-01-04 13:50 UTC, Justas383 requested changes
kažkur apie 750px pločio, tavo nav bar pradeda važiuoti į šoną ir nebesilygiuoja ties viduriu. tai šitą reikėtų sutvarkyti.. taip pat, heading nesilygiuoja ties viduriu, visas sukritęs į kairį šoną. 
Plius: šrifto storis, noretusi storesnio.  
Ties 756px, nuotraukos pradeda lygiuotis ne pagal centra, o kairėje pusėje. Dešinėje lieka balta erdvė. 👍

2021-01-05 11:03 UTC, arturas-vei approved these changes, later dismissed

2021-01-05 18:21 UTC, VytautasKaz requested changes
Tos pačios bėdos, kurias pastebėjo Justas, tik dar noriu pridėti, kad kažkodėl nuotraukos palenda po Logos CONTENT ir Footer CONTENT sekcijomis.

2021-01-05 18:24 UTC, VytautasKaz submitted a review, later dismissed

2021-01-05 20:55 UTC, Justas383 submitted a review, later dismissed

2021-01-05 22:44 UTC, belauzas requested changes
Need to fix 👍

2021-01-05 22:44 UTC, belauzas commented on index.html
> +                    <div class="">
Atrodo, lyg šis elementas būtų nereikalingas 🤔 Nes neturi jokio stiliaus.

2021-01-05 22:44 UTC, belauzas commented on index.html
> +                    <div class="project-selector">
Viską kas susiję su projekto galerija iškelti į atskirą `.row > .col-12`. t.y.

```
<div class="row">
    <div class="col-xs-12">
        H2 + P
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
        GALLERY
    </div>
</div>
```

2021-01-05 22:44 UTC, belauzas commented on index.html
> +                        <h1>Our Latest Featured Projects</h1>
Viename puslapyje **negali** būti daugiau nei vienas `<h1>` elementas -> keisti į `<h2>`.

P.S. peržiūrėti projektą ir jei tai kartojasi kitose sekcijose - sukurti atitinkamai taisimui skirtas užduotis (kiekvienai sekcijai atskirą užduotį).

2021-01-05 22:44 UTC, belauzas commented on css/components/projects.css
> +    height: 744.25px;
Kam fiksuoti elemento aukštį? 🤔🤔 Išmetame ir tegul pats elementas derinasi prie jame esančio turinio.

2021-01-05 22:44 UTC, belauzas commented on index.html
> +                        <div class="projects-design">
`.projects-design` klasė nėra aprašyta, todėl griūna dizainas.

2021-01-06 13:12 UTC, vikontrimaite requested changes
Super atrodo, tik keli smulkūs pasiūlymai! :smile:

2021-01-06 13:12 UTC, skrendam commented on css/components/projects.css
> +.projects-p {
Tarp `heading` ir `p` norėtųsi kiek mažesnio tarpo :smiley:

2021-01-06 13:12 UTC, vikontrimaite commented on css/components/projects.css
> +    font-weight: bold;
Man atrodo per daug stipriai `bold` šitas meniu. Pabandyk `font-weight` uždėti mažesnį nei `700` (aka `bold`) (jei ką, prie `variables.css` rasi šiuo metu jau aprašytus `font-weight`'us, jei nėra tau reikiamo, gali apsirašyti :smile:

2021-01-06 13:12 UTC, vikontrimaite commented on css/components/projects.css
> +.design-name {
čia man irgi norėtųsi vos kiek mažiau bold'o :)

2021-01-06 13:12 UTC, vikontrimaite commented on css/components/projects.css
> +    font-size: 16px;
o čia norėtųsi kiek mažesnio šrifto dydžio, nes toks didesnis atrodo ir labiau bold'iškesnis :smiley:

2021-01-06 13:12 UTC, vikontrimaite commented on css/components/projects.css
> +.design-img {
ant screen width 576px turėtų būti mažesnio dydžio paveiksliukai, nei kad ant 320px screen width, ir tik nuo šito didėja paveiksliukas didėjant ekrano dydžiui (taip bent jau orginale, man šiaip tinka ir tavo variantas :+1:  :smile: )

2021-01-06 13:12 UTC, vikontrimaite commented on css/components/projects.css
> +.design-img {
+ ant 1200px screen width pas tave vienoje eilėje pradeda tilpti 3 paveiksliukai, orginale  max du paveiksliukai vienoje eilutėje būna (net ir nuo 1200px screen width ir toliau)

2021-01-06 13:12 UTC, vikontrimaite commented on css/components/projects.css
> +    cursor: pointer;
čia kietai padarei, bet jaučiu reiks `a` daryti, nes čia nuorodos :smile:

2021-01-06 13:13 UTC, vikontrimaite commented
Ir kai padarai kažką konkretaus, ką prašė pakeisti, spausk 'resolve conversation', kad neberodytų :)

2021-01-10 18:38 UTC, Justas383 submitted a review, later dismissed

2021-03-28 13:47 UTC, merged