Create numbers section closes #5
front-end-by-rimantas/20-grupe-portfolio-personal pull request #51
Opened 2021-01-04 09:23 UTC by vikontrimaite

static numbers section:
-position elements
-responsive

2021-01-04 13:40 UTC, Justas383 requested changes
Norėtųsi jog skaičiai nesilygiuotų ties kaire puse, nes mažinant ekrano plotį, keistai žiūris, kai 2.3.4 elementai juda daug, o pats pirmas beveik statinis(tikiuosi suprasi apie ką aš). ir šiektiek reikėtų sumažinti tarpus tarp elementų

2021-01-04 15:08 UTC, VytautasKaz requested changes
Elementai ant plačiausio ekrano turėtų sutilpt į, atrodo, 1170px, nes kol kas atrodo, kad išeina už ribų, kuriose yra visas kitas aukščiau/žemiau esantis turinys.

2021-01-04 17:03 UTC, Justas383 approved these changes, later dismissed

2021-01-05 08:31 UTC, VytautasKaz approved these changes

2021-01-05 08:32 UTC, Justas383 approved these changes

2021-01-05 08:46 UTC, justasga approved these changes

2021-01-05 08:47 UTC, merged