Plan prices #8
front-end-by-rimantas/20-grupe-portfolio-personal pull request #71
Opened 2021-01-05 20:39 UTC by Justas383

Labas vakaras, prasau įvertinit kaip veikia responsive ir visą kitą. Kolkas nenaudojau jokio .js

2021-01-05 22:51 UTC, justasga requested changes
Šiaip viskas kaip ir ok, tik kaip pats discorde rašei kuomet du stulpeliai atsiranda tarpas ir dar kai susimažini dydį iki 500px pas tave margins atrodo didesni(40px) nei originaliam (10px)

2021-01-05 22:51 UTC, belauzas requested changes
Need to fix 👍

2021-01-05 22:51 UTC, belauzas commented on index.html
> +                    <section class="about-section">
Kodėl yra paliesta sekcija, kuri nėra užduoties dalis? 🤔 Darbas ne pagal planą - tiesioginis kelias link gint conflict'ų... 😥

2021-01-05 22:51 UTC, belauzas commented on index.html
> +                        <section class="about-section">
Kodėl yra paliesta sekcija, kuri nėra užduoties dalis? 🤔 Darbas ne pagal planą - tiesioginis kelias link gint conflict'ų... 😥

2021-01-05 22:51 UTC, belauzas commented on index.html
> +                <div class="col-xs-12 plans-main">
Viską kas susiję su pricing sąrašu iškelti į atskirą `.row > .col-12`. t.y.

```
<div class="row">
    <div class="col-xs-12">
        H2 + P
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
        PRICING
    </div>
</div>
```

2021-01-05 22:51 UTC, belauzas commented on index.html
> +                    <h1>Choose Your Plan</h1>
Viename puslapyje **negali** būti daugiau nei vienas `<h1>` elementas -> keisti į `<h2>`.

P.S. peržiūrėti projektą ir jei tai kartojasi kitose sekcijose - sukurti atitinkamai taisimui skirtas užduotis (kiekvienai sekcijai atskirą užduotį).

2021-01-06 13:24 UTC, vikontrimaite requested changes
Vau, labai gerai padirbėjai! Super atrodo pa'hover'inus :smile: :+1:  !
Man tik bendrai žiūrint norisi kiek mažesnio šrifto, mažiau bold'iškumo, bei didesnių tarpų tarp visų tų užrašų lentelėje :)
Beje, ant 320px 'buy now' iškeliauja į dešinę :thinking:  va taip https://ibb.co/tQh8HKx . Bet 400px jau viskas vėl tvarkoj.

2021-01-06 13:52 UTC, Justas383 commented on index.html
> +                        <section class="about-section">
ar turi mintyje jog ši sekcija nėra aprašyta issue aprašyme ar man reikėtu nenaudoti <section> tago?

2021-01-06 15:03 UTC, Justas383 commented on index.html
> +                <div class="col-xs-12 plans-main">
padariau pakeitimu, tikiuosi supratau teisingai ka reiketu padaryt 🔢

2021-01-06 19:33 UTC, belauzas commented on .vscode/settings.json
> +}
į `.gitignore` įtraukti `.vscode` eilutę

2021-01-06 19:33 UTC, belauzas commented on index.html
> +                        <section class="about-section">
neaprašyta prie užduoties 👍 nes tvarkingu atveju dirbame tik su viena sekcija/komponentu

2021-01-06 19:33 UTC, belauzas commented on index.html
> +                <div class="col-xs-12 plans-main">
nelabai...
pas tave buvo
```
<div class="row">
    <div class="col-xs-12">
        H2 + P
        PRICING
    </div>
</div>
``` 
Ir mano siūlymas yra turėti dvi `.row` dalis.
Šiuo metu, vis vien palikta vienas `.row`, kuriame yra daugiau turinio nei tik vienas 12 stulpelių elementas

2021-01-06 19:34 UTC, belauzas commented
Perrašiau HTML 🎅

2021-01-07 17:21 UTC, vikontrimaite submitted a review, later dismissed
Super!

2021-01-08 11:25 UTC, VytautasKaz approved these changes, later dismissed
Good to go!

2021-01-08 13:11 UTC, belauzas requested changes

2021-01-08 13:11 UTC, belauzas commented on .vscode/settings.json
> +}
Nope, vis dar nesutvarkyta 😬

2021-01-08 14:03 UTC, VytautasKaz approved these changes
Bye bye, liveserver.

2021-01-08 16:46 UTC, vikontrimaite approved these changes
:+1:

2021-01-09 14:57 UTC, belauzas approved these changes
🤞

2021-01-09 21:13 UTC, justasga approved these changes
Mano akimis tai t

2021-01-09 21:13 UTC, merged