Blog
front-end-by-rimantas/20-grupe-portfolio-personal pull request #74
Opened 2021-01-06 10:56 UTC by VytautasKaz

2021-01-06 13:32 UTC, vikontrimaite requested changes
Super padirbėjai, labai gerai atrodo! Tik vieną dalyką radau, ką galima patobulinti :smiley: :+1:

2021-01-06 13:32 UTC, vikontrimaite commented on css/components/blog.css
> +.blog-item > .social-info {
ant 320px screen width nebetelpa vienoje eilutėje :disappointed: https://ibb.co/QnYrmbv

2021-01-06 13:36 UTC, VytautasKaz commented on css/components/blog.css
> +.blog-item > .social-info {
Aš specialiai taip padariau, originale blogiau atrodo tas sukritimas.

2021-01-06 13:38 UTC, vikontrimaite commented on css/components/blog.css
> +.blog-item > .social-info {
Man kaip tik patinka vienoje eilutėje, bet patinka ir tavo variantas, ypač kai taip apgalvotas :smile:

2021-01-06 13:39 UTC, vikontrimaite commented on css/components/blog.css
> +.blog-item > .social-info {
mielai dabar paapprovinčiau, bet jaučiu tau reikės kažkokį bent mini commitą padaryt, tik kad leistų :thinking: :smile:

2021-01-06 13:40 UTC, vikontrimaite approved these changes

2021-01-06 13:46 UTC, VytautasKaz commented on css/components/blog.css
> +.blog-item > .social-info {
Pastėbėjau dabar, kad kiek skirtingai rodo, kai mažini savo ekrano plotį ir kai tiesiog įsijungi tą funkciją, kur parodo kaip mobilkėj atrodytų. Mažinant ekraną ant 320px jau būna praktiškai susilietę tie elementai, o mobilkėj normaliai atrodo, tai nežinau... :D

2021-01-06 14:07 UTC, vikontrimaite commented on css/components/blog.css
> +.blog-item > .social-info {
tau spręsti :smile: gal dar kiti ką nors patars? :thinking:

2021-01-06 19:15 UTC, justasga approved these changes

2021-01-07 01:31 UTC, arturas-vei approved these changes

2021-01-07 01:31 UTC, merged